# Generated by Django 2.2.1 on 2019-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_auto_20191215_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='imgUrl',
            field=models.CharField(help_text='the profile url:', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='imgUrl',
            field=models.CharField(help_text='the profile url:', max_length=200),
        ),
    ]
